name: AI PR Review
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  review:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: KarloK34/pr-reviewer@pr-reviewer-v3
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
